// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'content': string;
  'country': string;
  'exclusionIcon': string;
  'gender': string;
  'genderIcon': string;
  'icons': string;
  'links': string;
  'overlay': string;
  'overview': string;
  'poster': string;
  'posterContainer': string;
  'runtime': string;
  'searchResult': string;
  'statusContainer': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
